In [2]:
import numpy as np

In [3]:
import array

In [ ]:
#array

In [4]:
np.array([1,2,3,4,5,6,7,8])#dataset in numeric

array([1, 2, 3, 4, 5, 6, 7, 8])

In [5]:
type(np.array([1,2,3,4,5,6,7,8]))

numpy.ndarray

In [6]:
np.array([1,2,3,4,5,6,7,8,"shiks",3+5j])#datastring in string

array(['1', '2', '3', '4', '5', '6', '7', '8', 'shiks', '(3+5j)'],
      dtype='<U21')

In [7]:
np.array([1,2,3,4,5.0])#all data in floating point
#upcasts all data automatically

array([1., 2., 3., 4., 5.])

In [9]:
np.array([[1,3],[1,2]])

array([[1, 3],
       [1, 2]])

In [10]:
np.array([[1,3],[1,2],[1,3]])

array([[1, 3],
       [1, 2],
       [1, 3]])

In [11]:
np.array([[1,3],[1,2],[11,12,13]])

<ipython-input-11-3788be42eef3>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  np.array([[1,3],[1,2],[11,12,13]])


array([list([1, 3]), list([1, 2]), list([11, 12, 13])], dtype=object)

In [13]:
np.array([[[1,3],[1,2]],[[1,3],[1,2]]])

array([[[1, 3],
        [1, 2]],

       [[1, 3],
        [1, 2]]])

In [14]:
np.array([1,2,3],ndmin = 3)

array([[[1, 2, 3]]])

In [16]:
np.array([1,2,3+2j],dtype = complex)

array([1.+0.j, 2.+0.j, 3.+2.j])

In [31]:
arr=np.array([(1,2),(3,4)],dtype=[("a","<i4"),("b","<i8")])

In [32]:
arr

array([(1, 2), (3, 4)], dtype=[('a', '<i4'), ('b', '<i8')])

In [33]:
arr[0]

(1, 2)

In [34]:
arr[0][0]

1

In [35]:
type(arr[0][0])

numpy.int32

In [36]:
type(arr[0][1])

numpy.int64

In [38]:
type(arr[1][0])

numpy.int32

In [39]:
arr=np.array([(1,2),(3,4)])

In [40]:
arr

array([[1, 2],
       [3, 4]])

In [43]:
type(arr[1][1])

numpy.int64

In [42]:
arr[1]

array([3, 4])

In [ ]:
#matrices

In [44]:
np.mat(arr)

matrix([[1, 2],
        [3, 4]])

In [51]:
mat=np.matrix(arr)

In [46]:
l=[1,2,3,4,5,6,7]

In [47]:
np.array(l)

array([1, 2, 3, 4, 5, 6, 7])

In [48]:
np.asarray(l)

array([1, 2, 3, 4, 5, 6, 7])

In [49]:
np.asanyarray(l)

array([1, 2, 3, 4, 5, 6, 7])

In [52]:
np.asanyarray(mat)

matrix([[1, 2],
        [3, 4]])

In [53]:
mat

matrix([[1, 2],
        [3, 4]])

In [54]:
np.asarray(mat)

array([[1, 2],
       [3, 4]])

In [56]:
issubclass(np.matrix , np.ndarray)
#are matrix a subclass of ndarray

True

In [57]:
issubclass(np.ndarray , np.matrix)
#reverse cant be true

False

In [58]:
arr

array([[1, 2],
       [3, 4]])

In [59]:
a=arr
#shallow copy,data will change

In [60]:
b=np.copy(arr)
#deep copy, data unaffected

In [61]:
b

array([[1, 2],
       [3, 4]])

In [62]:
arr[0][0]=67
#arrat elements are mutable

In [63]:
arr

array([[67,  2],
       [ 3,  4]])

In [64]:
a#changed

array([[67,  2],
       [ 3,  4]])

In [65]:
b#not changed

array([[1, 2],
       [3, 4]])

In [66]:
arr[0:10]#1st and 2nd element printed

array([[67,  2],
       [ 3,  4]])

In [67]:
arr[-1]

array([3, 4])

In [68]:
for i in arr:
    print(i)

[67  2]
[3 4]


In [71]:
type(np.fromfunction(lambda i, j : i==j , (4,4)))

numpy.ndarray

In [74]:
np.fromfunction(lambda i, j : i==j , (4,4))
#(4,4) represents size of array

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False],
       [False, False, False,  True]])

In [76]:
np.fromfunction(lambda i, j : i*j , (3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [78]:
np.fromfunction(lambda i, j : i**j , (3,3))

array([[1., 0., 0.],
       [1., 1., 1.],
       [1., 2., 4.]])

In [79]:
np.fromfunction(lambda i, j : i/j , (3,3))

<ipython-input-79-0f56e7814011>:1: RuntimeWarning: divide by zero encountered in true_divide
  np.fromfunction(lambda i, j : i/j , (3,3))
<ipython-input-79-0f56e7814011>:1: RuntimeWarning: invalid value encountered in true_divide
  np.fromfunction(lambda i, j : i/j , (3,3))


array([[nan, 0. , 0. ],
       [inf, 1. , 0.5],
       [inf, 2. , 1. ]])

In [80]:
[i*i for i in range(5)]

[0, 1, 4, 9, 16]

In [85]:
gen=(i*i for i in range(5))

In [82]:
def test(x):
    yield(x)

In [83]:
test(5)

<generator object test at 0x7ff7fc154660>

In [86]:
gen

<generator object <genexpr> at 0x7ff7fc1549e0>

In [87]:
np.fromiter(gen,dtype=int)

array([ 0,  1,  4,  9, 16])

In [88]:
np.fromiter(range(5) ,dtype=int)

array([0, 1, 2, 3, 4])

In [91]:
# gen 
for i in gen:
    print(i)

In [98]:
np.fromstring("1,2,4,56,67", sep=",", dtype=int)

array([ 1,  2,  4, 56, 67])

In [99]:
np.fromstring("12 23 44 32",sep=" ", dtype=complex)

array([12.+0.j, 23.+0.j, 44.+0.j, 32.+0.j])

In [100]:
l=[1,2,3,4,5,6,7,8]

In [102]:
arr = np.array(l)

In [108]:
arr1 = np.array([[1,2,3,4],[2,3,4,5],[1,4,5,6]])

In [109]:
arr1

array([[1, 2, 3, 4],
       [2, 3, 4, 5],
       [1, 4, 5, 6]])

In [105]:
type(arr)

numpy.ndarray

In [107]:
arr.ndim

1

In [110]:
arr1.ndim#can be represnted in 2d

2

In [111]:
arr1.size#total number of element

12

In [112]:
arr1.shape

(3, 4)

In [113]:
arr1.dtype

dtype('int64')

In [114]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [115]:
arr.size

8

In [116]:
arr.ndim#can be represnted in 1d

1

In [117]:
arr.shape

(8,)

In [126]:
arr2=np.array([[[1,2,3,4],[5,6,7,8]],[[1,2,3,4],[5,6,7,8]]])

In [127]:
arr2

array([[[1, 2, 3, 4],
        [5, 6, 7, 8]],

       [[1, 2, 3, 4],
        [5, 6, 7, 8]]])

In [128]:
arr2.ndim

3

In [129]:
arr2.size

16

In [130]:
arr2.shape#we have 2  (2x4) data

(2, 2, 4)

In [133]:
list(range(5.5))

TypeError: 'float' object cannot be interpreted as an integer

In [137]:
np.arange(6.6, 9 ,0.3)
#accepts upperbound unlike range fn?

array([6.6, 6.9, 7.2, 7.5, 7.8, 8.1, 8.4, 8.7, 9. ])

In [138]:
np.arange(9 , 6.6 , -0.3)

array([9. , 8.7, 8.4, 8.1, 7.8, 7.5, 7.2, 6.9, 6.6])

In [144]:
np.arange(1,9)
#doenst accept upperbound?no it doesnt accept upper bound

array([1, 2, 3, 4, 5, 6, 7, 8])

In [146]:
np.linspace(1,2,5)
#generates data between 2 points here 1 and 2, and 
#no. of data generated is 5
#seperated distance btw 2 points into 5 eual parts

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [148]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [149]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [150]:
np.zeros((2,5,4))#5x4 in 2 array

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [151]:
np.zeros((2,5,4,1))#4x1 5times in 2 array

array([[[[0.],
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         [0.]]],


       [[[0.],
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         [0.]]]])

In [152]:
np.ones(4)

array([1., 1., 1., 1.])

In [155]:
np.ones((2,3,1))+5

array([[[6.],
        [6.],
        [6.]],

       [[6.],
        [6.],
        [6.]]])

In [156]:
np.empty(5)

array([0., 0., 0., 0., 0.])

In [160]:
np.empty((3,3))#random no. each time

array([[9. , 8.7, 8.4],
       [8.1, 7.8, 7.5],
       [7.2, 6.9, 6.6]])

In [161]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
#understand, do it then leave it, you will recall later

In [166]:
np.linspace(2,4,4, endpoint=False, axis=0)

array([2. , 2.5, 3. , 3.5])

In [171]:
np.linspace([1,6],1, endpoint=False, axis=1)

array([[1. , 1. , 1. , 1. , 1. , 1. , 1. , 1. , 1. , 1. , 1. , 1. , 1. ,
        1. , 1. , 1. , 1. , 1. , 1. , 1. , 1. , 1. , 1. , 1. , 1. , 1. ,
        1. , 1. , 1. , 1. , 1. , 1. , 1. , 1. , 1. , 1. , 1. , 1. , 1. ,
        1. , 1. , 1. , 1. , 1. , 1. , 1. , 1. , 1. , 1. , 1. ],
       [6. , 5.9, 5.8, 5.7, 5.6, 5.5, 5.4, 5.3, 5.2, 5.1, 5. , 4.9, 4.8,
        4.7, 4.6, 4.5, 4.4, 4.3, 4.2, 4.1, 4. , 3.9, 3.8, 3.7, 3.6, 3.5,
        3.4, 3.3, 3.2, 3.1, 3. , 2.9, 2.8, 2.7, 2.6, 2.5, 2.4, 2.3, 2.2,
        2.1, 2. , 1.9, 1.8, 1.7, 1.6, 1.5, 1.4, 1.3, 1.2, 1.1]])

In [172]:
np.logspace(2,3,5)#log100=10 for base 2 and log1000=3 for base 10

array([ 100.        ,  177.827941  ,  316.22776602,  562.34132519,
       1000.        ])

In [177]:
np.logspace([2],[3],axis=0)

array([[ 100.        ],
       [ 104.81131342],
       [ 109.8541142 ],
       [ 115.13953993],
       [ 120.67926406],
       [ 126.48552169],
       [ 132.57113656],
       [ 138.94954944],
       [ 145.63484775],
       [ 152.64179672],
       [ 159.98587196],
       [ 167.68329368],
       [ 175.75106249],
       [ 184.20699693],
       [ 193.06977289],
       [ 202.35896477],
       [ 212.09508879],
       [ 222.29964825],
       [ 232.99518105],
       [ 244.20530945],
       [ 255.95479227],
       [ 268.26957953],
       [ 281.1768698 ],
       [ 294.70517026],
       [ 308.88435965],
       [ 323.74575428],
       [ 339.32217719],
       [ 355.64803062],
       [ 372.75937203],
       [ 390.69399371],
       [ 409.49150624],
       [ 429.19342601],
       [ 449.8432669 ],
       [ 471.48663635],
       [ 494.17133613],
       [ 517.94746792],
       [ 542.86754393],
       [ 568.9866029 ],
       [ 596.36233166],
       [ 625.05519253],
       [ 655.12855686],
       [ 686.648

In [178]:
d=np.linspace(4,7,40)

In [179]:
d

array([4.        , 4.07692308, 4.15384615, 4.23076923, 4.30769231,
       4.38461538, 4.46153846, 4.53846154, 4.61538462, 4.69230769,
       4.76923077, 4.84615385, 4.92307692, 5.        , 5.07692308,
       5.15384615, 5.23076923, 5.30769231, 5.38461538, 5.46153846,
       5.53846154, 5.61538462, 5.69230769, 5.76923077, 5.84615385,
       5.92307692, 6.        , 6.07692308, 6.15384615, 6.23076923,
       6.30769231, 6.38461538, 6.46153846, 6.53846154, 6.61538462,
       6.69230769, 6.76923077, 6.84615385, 6.92307692, 7.        ])

In [180]:
d.ndim

1

In [181]:
d.shape

(40,)

In [183]:
d.reshape(40,1)

array([[4.        ],
       [4.07692308],
       [4.15384615],
       [4.23076923],
       [4.30769231],
       [4.38461538],
       [4.46153846],
       [4.53846154],
       [4.61538462],
       [4.69230769],
       [4.76923077],
       [4.84615385],
       [4.92307692],
       [5.        ],
       [5.07692308],
       [5.15384615],
       [5.23076923],
       [5.30769231],
       [5.38461538],
       [5.46153846],
       [5.53846154],
       [5.61538462],
       [5.69230769],
       [5.76923077],
       [5.84615385],
       [5.92307692],
       [6.        ],
       [6.07692308],
       [6.15384615],
       [6.23076923],
       [6.30769231],
       [6.38461538],
       [6.46153846],
       [6.53846154],
       [6.61538462],
       [6.69230769],
       [6.76923077],
       [6.84615385],
       [6.92307692],
       [7.        ]])

In [186]:
d.reshape(2,1,20)#2 matrix of 1x20
#data=40 was divided by 2 to get 20 in linspace

array([[[4.        , 4.07692308, 4.15384615, 4.23076923, 4.30769231,
         4.38461538, 4.46153846, 4.53846154, 4.61538462, 4.69230769,
         4.76923077, 4.84615385, 4.92307692, 5.        , 5.07692308,
         5.15384615, 5.23076923, 5.30769231, 5.38461538, 5.46153846]],

       [[5.53846154, 5.61538462, 5.69230769, 5.76923077, 5.84615385,
         5.92307692, 6.        , 6.07692308, 6.15384615, 6.23076923,
         6.30769231, 6.38461538, 6.46153846, 6.53846154, 6.61538462,
         6.69230769, 6.76923077, 6.84615385, 6.92307692, 7.        ]]])

In [187]:
d.reshape(3,1,20)#cannot reshape array of size 40 into shape (3,1,20)

ValueError: cannot reshape array of size 40 into shape (3,1,20)

In [188]:
d.reshape(1,4,10)

array([[[4.        , 4.07692308, 4.15384615, 4.23076923, 4.30769231,
         4.38461538, 4.46153846, 4.53846154, 4.61538462, 4.69230769],
        [4.76923077, 4.84615385, 4.92307692, 5.        , 5.07692308,
         5.15384615, 5.23076923, 5.30769231, 5.38461538, 5.46153846],
        [5.53846154, 5.61538462, 5.69230769, 5.76923077, 5.84615385,
         5.92307692, 6.        , 6.07692308, 6.15384615, 6.23076923],
        [6.30769231, 6.38461538, 6.46153846, 6.53846154, 6.61538462,
         6.69230769, 6.76923077, 6.84615385, 6.92307692, 7.        ]]])

In [ ]:
#reshape is useful fn.

In [192]:
np.random.rand(3)#normal distribution

array([0.13135569, 0.3185291 , 0.68685217])

In [193]:
np.random.randn(5)#std normal dist, mean 0,std deviation=1

array([-0.11960992, -0.55188052,  1.39104964, -0.46682705, -0.97743103])

In [195]:
np.random.randn(2,2,3)

array([[[ 0.03388561, -2.02996381,  0.15368559],
        [-0.29312749,  1.33483075,  1.10508023]],

       [[ 0.66668264,  0.36046564,  0.96361912],
        [-0.12845064, -0.43743696,  0.46664168]]])

In [202]:
np.random.randint(5,10)
#genrated no.between 5 and 10

5

In [203]:
np.random.randint(5,60,(4,4))
#generated 4x4 matrix with data btw 5 and 60

array([[37, 10, 20, 53],
       [49, 38, 15, 17],
       [39, 43,  6, 26],
       [ 6, 24, 51, 20]])

In [204]:
arr = np.random.randint(3,9,(3,3))

In [205]:
arr

array([[8, 8, 5],
       [3, 6, 8],
       [5, 6, 3]])

In [207]:
arr.reshape(1,9)

array([[8, 8, 5, 3, 6, 8, 5, 6, 3]])

In [208]:
arr.reshape(9,1)

array([[8],
       [8],
       [5],
       [3],
       [6],
       [8],
       [5],
       [6],
       [3]])

In [209]:
arr.reshape(1,1,9)

array([[[8, 8, 5, 3, 6, 8, 5, 6, 3]]])

In [211]:
arr.reshape(2,3,3)

ValueError: cannot reshape array of size 9 into shape (2,3,3)

In [212]:
arr.reshape(3,3,1)

array([[[8],
        [8],
        [5]],

       [[3],
        [6],
        [8]],

       [[5],
        [6],
        [3]]])

In [218]:
arr.reshape(3,-1)#assuemes 3x3

array([[8, 8, 5],
       [3, 6, 8],
       [5, 6, 3]])

In [220]:
arr.reshape(1,-12334)#assuems 1x9

array([[8, 8, 5, 3, 6, 8, 5, 6, 3]])

In [221]:
arr.max()

8

In [222]:
arr.min()

3

In [225]:
arr=np.random.randint(4,100, (5,5))

In [226]:
arr

array([[57, 58, 94, 73,  6],
       [67, 90, 74, 76,  5],
       [74, 85, 92, 84, 36],
       [76, 36, 51, 95, 24],
       [60, 25,  4,  6, 34]])

In [227]:
arr[3:,3:]#arr[row_no : , column_no : ]

array([[95, 24],
       [ 6, 34]])

In [228]:
arr[:,[1,3]]#for all rows in column 1 and 3

array([[58, 73],
       [90, 76],
       [85, 84],
       [36, 95],
       [25,  6]])

In [229]:
arr

array([[57, 58, 94, 73,  6],
       [67, 90, 74, 76,  5],
       [74, 85, 92, 84, 36],
       [76, 36, 51, 95, 24],
       [60, 25,  4,  6, 34]])

In [230]:
arr>10

array([[ True,  True,  True,  True, False],
       [ True,  True,  True,  True, False],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True, False, False,  True]])

In [232]:
arr[arr>10]

array([57, 58, 94, 73, 67, 90, 74, 76, 74, 85, 92, 84, 36, 76, 36, 51, 95,
       24, 60, 25, 34])

In [233]:
for i in arr:
    for j in i:
        print(j)

57
58
94
73
6
67
90
74
76
5
74
85
92
84
36
76
36
51
95
24
60
25
4
6
34


In [235]:
arr*arr

array([[3249, 3364, 8836, 5329,   36],
       [4489, 8100, 5476, 5776,   25],
       [5476, 7225, 8464, 7056, 1296],
       [5776, 1296, 2601, 9025,  576],
       [3600,  625,   16,   36, 1156]])

In [236]:
arr1=np.random.randint(2,4,(3,3))

In [237]:
arr2=np.random.randint(2,4,(3,3))

In [238]:
arr1

array([[2, 2, 2],
       [3, 2, 3],
       [3, 2, 3]])

In [239]:
arr2

array([[3, 2, 3],
       [2, 3, 2],
       [3, 3, 3]])

In [240]:
arr1*arr2#direct index wise multiplication

array([[6, 4, 6],
       [6, 6, 6],
       [9, 6, 9]])

In [242]:
arr1@arr2#matrix multiplication

array([[16, 16, 16],
       [22, 21, 22],
       [22, 21, 22]])

In [243]:
arr**arr

array([[ 4951460147845608313, -6629298651489370112,                    0,
        -3116162374727926391,                46656],
       [ 8037740809528595931,                    0,                    0,
                           0,                 3125],
       [                   0,  3792227444683241861,                    0,
                           0,                    0],
       [                   0,                    0,  2823291043684304491,
        -3660930864499998817,                    0],
       [                   0, -6776596920136667815,                  256,
                       46656, -5296008294479953920]])

In [244]:
arr**2

array([[3249, 3364, 8836, 5329,   36],
       [4489, 8100, 5476, 5776,   25],
       [5476, 7225, 8464, 7056, 1296],
       [5776, 1296, 2601, 9025,  576],
       [3600,  625,   16,   36, 1156]])

In [ ]:
#Braodcasting

In [245]:
arr=np.zeros((3,4))

In [246]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [247]:
a=np.array([1,2,3,4])

In [248]:
a

array([1, 2, 3, 4])

In [249]:
arr+a#a broadcasted on each row of arr

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [250]:
arr+5#5 broadcasted to each element

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [252]:
a+arr

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [253]:
b = np.array([5,6,7])

In [255]:
b.reshape(3,1) + arr#column wise broadcasting

array([[5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [260]:
b = np.array([[5,6,7]])#1d not acceptable
#has to create 2d array

In [261]:
b.T#transpose

array([[5],
       [6],
       [7]])

In [262]:
b.T + arr

array([[5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [264]:
arr=np.random.rand(5,4)

In [265]:
arr

array([[0.49359905, 0.87966419, 0.18641744, 0.88992917],
       [0.19027014, 0.03608885, 0.02252081, 0.82331753],
       [0.72620436, 0.54232276, 0.29379982, 0.70009952],
       [0.26459238, 0.52608483, 0.45544825, 0.68931151],
       [0.35646702, 0.24204586, 0.87536567, 0.84355415]])

In [266]:
np.sqrt(arr)

array([[0.70256604, 0.93790415, 0.43176085, 0.94336057],
       [0.43619965, 0.18997067, 0.15006935, 0.90736846],
       [0.85217625, 0.73642567, 0.54203304, 0.8367195 ],
       [0.51438544, 0.72531705, 0.67486906, 0.83024786],
       [0.59704859, 0.49198157, 0.93560979, 0.91845204]])

In [267]:
np.exp(arr)

array([[1.63820159, 2.41009023, 1.20492513, 2.43495717],
       [1.2095763 , 1.03674796, 1.02277632, 2.2780448 ],
       [2.06721929, 1.71999738, 1.34151533, 2.01395313],
       [1.30289978, 1.6922937 , 1.57688006, 1.99234335],
       [1.42827442, 1.27385261, 2.39975265, 2.32461434]])

In [268]:
np.log10(arr)

array([[-0.30662569, -0.05568309, -0.72951347, -0.05064456],
       [-0.72062937, -1.4426269 , -1.64741597, -0.08443264],
       [-0.13894115, -0.26574216, -0.53194848, -0.15484022],
       [-0.57742267, -0.27894422, -0.34156097, -0.16158447],
       [-0.44798065, -0.61610234, -0.05781049, -0.07388703]])

In [271]:
arr1=np.random.randint(2,5,(5,5))

In [274]:
np.log2(arr1)

array([[1.5849625, 2.       , 1.5849625, 1.       , 1.5849625],
       [1.5849625, 1.5849625, 1.5849625, 1.5849625, 1.5849625],
       [1.       , 2.       , 1.5849625, 1.5849625, 2.       ],
       [2.       , 1.5849625, 2.       , 2.       , 1.       ],
       [1.5849625, 1.       , 2.       , 1.       , 1.       ]])

In [275]:
arr1

array([[3, 4, 3, 2, 3],
       [3, 3, 3, 3, 3],
       [2, 4, 3, 3, 4],
       [4, 3, 4, 4, 2],
       [3, 2, 4, 2, 2]])

In [282]:
np.random.seed(13)
np.random.randn(2,4)#will not change

array([[-0.71239066,  0.75376638, -0.04450308,  0.45181234],
       [ 1.34510171,  0.53233789,  1.3501879 ,  0.86121137]])